[project]
name = "djangoproject"
version = "0.1.0"
description = ""
authors = [
    {name = "milklolo",email = "33389126+milklolo@users.noreply.github.com"}
]
requires-python = "^3.11"
dependencies = [
    "django (>=4.2,<5.0)",
    "djangorestframework (>=3.16.1,<4.0.0)"
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
[tool.poetry]
package-mode = false