# Generated by Django 4.2.28 on 2026-03-14 06:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('test1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_photo1',
            field=models.ImageField(blank=True, help_text='商品照片1', null=True, upload_to='images/subscriber/', verbose_name='商品照片1'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_photo2',
            field=models.ImageField(blank=True, help_text='商品照片2', null=True, upload_to='images/subscriber/', verbose_name='商品照片2'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_photo3',
            field=models.ImageField(blank=True, help_text='商品照片3', null=True, upload_to='images/subscriber/', verbose_name='商品照片3'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_photo4',
            field=models.ImageField(blank=True, help_text='商品照片4', null=True, upload_to='images/subscriber/', verbose_name='商品照片4'),
        ),
        migrations.AlterField(
            model_name='order',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='test1.product'),
        ),
        migrations.AlterField(
            model_name='order',
            name='sales',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='test1.sales'),
        ),
    ]
