# Generated by Django 4.2.28 on 2026-03-14 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test1', '0003_remove_order_product_remove_order_quantity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='product_photo1',
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_photo2',
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_photo3',
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_photo4',
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
