# Generated by Django 4.2.28 on 2026-03-14 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test1', '0004_remove_product_product_photo1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/'),
        ),
    ]
